# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          KimEJ
baseurl:        ""
url:            "https://kimej.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Eojin Kim
  url:          https://kimej.github.io/
  email:        kimuj5090@gmail.com  
  github:       KimEJ
  # twitter:      playpingpong

# Custom vars
# version:        3.4.1
# github:
#   repo:         https://github.com/iamleejihye/iamleejihye.github.io